# ===============================
# 1. CONFIGURACION DEL SERVIDOR
# ===============================
server.port=8081
server.servlet.context-path=/api

# ===============================
# 2. BASE DE DATOS (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/spotter_db
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# 3. JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# 4. GESTION DE ARCHIVOS (Multipart)
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# 5. SEGURIDAD (JWT)
# ===============================
security.jwt.secret-key=BGljrWuimrvfUWXiECV1JWPkPvvhYo6eZgNXQYvHnyY=
security.jwt.expiration-time=86400000

# ===============================
# 6. CLOUDINARY (pendiente)
# ===============================
# cloudinary.cloud-name=tu_nombre_cloud
# cloudinary.api-key=tu_api_key
# cloudinary.api-secret=tu_api_secret

# ===============================
# 7. SPRINGDOC / SWAGGER UI
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true
